# Generated by Django 4.1 on 2022-09-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_options_note_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
