# Generated by Django 4.1 on 2022-09-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated',
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(),
        ),
    ]
